services:
  api:
    volumes:
      - ../../../pelias/flyingdev-api:/code/pelias/api
      - /code/pelias/api/node_modules

    environment:
      - PELIAS_OPENSEARCH=true
    build:
      context: ../../../pelias/flyingdev-api
      dockerfile: Dockerfile
