services:
  api:
    volumes:
      - ../../../pelias/flyingdev-api:/code/pelias/api
      - /code/pelias/api/node_modules
      - ../../../pelias/flyingdev-dbclient:/code/pelias/api/node_modules/pelias-dbclient
    environment:
      - PELIAS_OPENSEARCH=true
    depends_on:
      - opensearch

  schema:
    volumes:
      - ../../../pelias/flyingdev-schema:/code/pelias/schema
      - ../../../pelias/flyingdev-dbclient:/code/pelias/schema/node_modules/pelias-dbclient
    environment:
      - PELIAS_OPENSEARCH=true
      - OPENSEARCH_NODE=http://opensearch:9200
    depends_on:
      - opensearch

  elasticsearch:
    scale: 0

  opensearch:
    image: opensearchproject/opensearch:1.3.14
    container_name: pelias-opensearch
    environment:
      - cluster.name=pelias
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
  whosonfirst:
    volumes:
      # Ensure node_modules inside the container stays container-managed
      - /code/pelias/whosonfirst/node_modules
      # Force pelias-dbclient to resolve to your local version
      - ../../../pelias/flyingdev-dbclient:/code/pelias/whosonfirst/node_modules/pelias-dbclient
    environment:
      - PELIAS_OPENSEARCH=true
      - OPENSEARCH_NODE=http://opensearch:9200
    depends_on:
      - opensearch
  dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.14
    container_name: pelias-opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["https://pelias-opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch


volumes:
  opensearch-data:
