services:
  api:
    volumes:
      - ../../../pelias/flyingdev-api:/code/pelias/api
      - /code/pelias/api/node_modules
      - ../../../pelias/flyingdev-dbclient:/code/pelias/api/node_modules/pelias-dbclient

  schema:
    volumes:
      - ../../../pelias/flyingdev-schema:/code/pelias/schema
      - /code/pelias/schema/node_modules
      - ../../../pelias/flyingdev-dbclient:/code/pelias/schema/node_modules/pelias-dbclient
